# Generated by Django 6.0.2 on 2026-05-28 05:47

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether appointments can be booked on this day')),
            ],
            options={
                'verbose_name_plural': 'Appointment Days',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Client phone number', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('featured_image', models.ImageField(blank=True, help_text='Main image displayed at the top of the page', null=True, upload_to='services/')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('category', models.CharField(blank=True, help_text='e.g., Patron in Chief, Executive Committe, Founders, etc', max_length=100)),
                ('job_title', models.CharField(help_text='e.g., Senior Team, Junior Team, Paralegal', max_length=255)),
                ('short_bio', models.TextField(blank=True, help_text='Brief personal statement or tagline (max 300 characters)', max_length=300)),
                ('professional_background', models.TextField(blank=True, help_text='Detailed professional background and biography')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(help_text='Professional photo of the team member', upload_to='team/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance on the team page (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this team member on the website')),
                ('specializations', models.CharField(blank=True, help_text='Comma-separated list of service', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Teams',
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/')),
                ('title', models.CharField(blank=True, help_text='Optional title for the image', max_length=255)),
                ('description', models.CharField(blank=True, help_text='Optional description for the image', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of images in gallery (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='pages.service')),
            ],
            options={
                'verbose_name_plural': 'Service Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailableHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='Window start time (e.g., 9:00 AM)')),
                ('end_time', models.TimeField(help_text='Window end time (e.g., 11:00 AM)')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_hours', to='pages.appointmentday')),
            ],
            options={
                'verbose_name_plural': 'Available Hours',
                'ordering': ['day', 'start_time'],
                'unique_together': {('day', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=20)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=60, help_text='Duration in minutes')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.service')),
            ],
            options={
                'verbose_name_plural': 'Appointments',
                'ordering': ['-appointment_date', '-appointment_time'],
                'unique_together': {('appointment_date', 'appointment_time')},
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for the blog post', null=True, upload_to='blogs/')),
                ('excerpt', models.TextField(help_text='Short summary of the blog post', max_length=500)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Main content of the blog post')),
                ('category', models.CharField(blank=True, help_text='Blog category/topic', max_length=100)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Whether this blog is visible on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ManyToManyField(blank=True, help_text='Select one or more team members as authors of this blog post', related_name='blogs', to='pages.team')),
            ],
            options={
                'verbose_name_plural': 'Blogs',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['-published_date'], name='pages_blog_publish_f142d8_idx'), models.Index(fields=['slug'], name='pages_blog_slug_09fc28_idx'), models.Index(fields=['is_published'], name='pages_blog_is_publ_b56172_idx')],
            },
        ),
    ]
