# Generated by Django 6.0.2 on 2026-05-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='job_title',
            field=models.CharField(blank=True, help_text='e.g., Senior Team, Junior Team, Paralegal', max_length=255, null=True),
        ),
    ]
