# Generated by Django 6.0.2 on 2026-05-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_team_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary of the service (max 500 characters)', max_length=500),
        ),
    ]
