# Generated by Django 6.0.2 on 2026-05-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_service_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='short_bio',
            field=models.TextField(blank=True, help_text='Brief personal statement or tagline (max 1000 characters)', max_length=1000),
        ),
    ]
