# Generated by Django 6.0.2 on 2026-05-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_team_short_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, help_text='Professional photo of the team member', upload_to='team/'),
        ),
    ]
