# Generated by Django 6.0.2 on 2026-05-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_team_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='panelist',
            field=models.CharField(blank=True, help_text='Panelist role or title if applicable (e.g., National Arbitrational Panelist, International Arbitrational Panelist, National Mediation Panelist, etc)', max_length=255),
        ),
    ]
