# Generated by Django 6.0.2 on 2026-06-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_team_panelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='about',
            field=models.TextField(blank=True, help_text='Details on experience, education, bio, etc'),
        ),
        migrations.AlterField(
            model_name='team',
            name='professional_background',
            field=models.TextField(blank=True, help_text='professional background '),
        ),
    ]
