# Generated by Django 6.0.2 on 2026-06-07 09:46

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_bulletin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('featured_image', models.ImageField(upload_to='events/')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('event_start_date', models.DateField(blank=True, null=True)),
                ('event_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
