# Generated by Django 6.0.2 on 2026-06-07 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_eventbooking_event_early_bird_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='event',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='pages.event'),
            preserve_default=False,
        ),
    ]
