# Generated by Django 6.0.2 on 2026-06-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_event_slug_eventbooking_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='', help_text='URL-friendly identifier', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
