# Generated by Django 6.0.2 on 2026-06-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='payment_reference_no',
        ),
        migrations.AddField(
            model_name='event',
            name='bank_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='swift_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='reference_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
