# Generated by Django 6.0.2 on 2026-06-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_eventbooking_payment_reference_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='hotel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
