# Generated by Django 6.0.2 on 2026-06-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_callbackrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='hotel',
        ),
    ]
