# Generated by Django 6.0.2 on 2026-06-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_remove_eventbooking_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bank_account_name',
            field=models.CharField(blank=True, default='Nepal International ADR Center', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='bank_account_type',
            field=models.CharField(blank=True, default='Savings Account', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='bank_address',
            field=models.CharField(blank=True, default='Sanima Bank, Kathmandu, Nepal', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='bank_name',
            field=models.CharField(blank=True, default='Sanima Bank Limited', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_prefix',
            field=models.CharField(default='ADR', help_text='Prefix for registration IDs (e.g., ADR → ADR-001)', max_length=10),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes for bank matching'),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='proof_file',
            field=models.FileField(blank=True, help_text='Upload wire transfer receipt / MT103', null=True, upload_to='proofs/'),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='proof_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='registration_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique registration ID (e.g., ADR-502)', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_verification', 'Pending Verification'), ('confirmed', 'Confirmed')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='reference_code',
            field=models.CharField(blank=True, help_text='Wire transfer reference number', max_length=255, null=True),
        ),
    ]
