# Generated by Django 6.0.2 on 2026-08-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_lookup_token_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='foreign_early_bird_usd',
            field=models.FloatField(blank=True, help_text='USD early-bird price (until August 2026)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='foreign_standard_usd',
            field=models.FloatField(blank=True, help_text='USD standard price', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='individual_price_npr',
            field=models.FloatField(blank=True, help_text='NPR price — Individual Fee', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='institutional_price_npr',
            field=models.FloatField(blank=True, help_text='NPR price — Institutional Fee', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='nepali_price_npr',
            field=models.FloatField(blank=True, help_text='NPR price for Nepalese participants (limited seats)', null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='participant_type',
            field=models.CharField(choices=[('nepali_scholars', 'Scholars, Academics & Students'), ('nepali_institutional', 'Institutional Fee'), ('nepali_individual', 'Individual Fee'), ('foreign_early_bird', 'Early Bird'), ('foreign_standard', 'Standard')], default='nepali_scholars', max_length=30),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='total_amount_display',
            field=models.CharField(blank=True, help_text='Human-readable total (e.g. NPR 50,000 or USD 400)', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='bank_account_name',
            field=models.CharField(blank=True, default='Nepal International A.D.R. Center', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='bank_name',
            field=models.CharField(blank=True, default='Sanima Bank Ltd.', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_prefix',
            field=models.CharField(default='NIAC', help_text='Prefix for registration IDs (e.g., NIAC → NIAC-001)', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='registration_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique registration ID (e.g., NIAC-502)', max_length=50, unique=True),
        ),
    ]
