"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
# load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-eyf#)cck(*3g(0l#gx#%#07rg917m!9d3b5i8!-1(wtsj9y(5o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['niac.org.np','localhost','niac.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_ckeditor_5',
    'corsheaders',
    'pages',
    'blogs',
    'storages',
    'wp_import',
    'django_cleanup.apps.CleanupConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




# Tell django-storages to use the S3Boto3 backend:
# STORAGES = {
#     "default": {
#         "BACKEND": "storages.backends.s3.S3Storage",
#         "OPTIONS": {
#             "access_key": os.getenv('AWS_ACCESS_KEY_ID'),
#             "secret_key": os.getenv('AWS_SECRET_ACCESS_KEY'),
#             "bucket_name": os.getenv('AWS_STORAGE_BUCKET_NAME'),
#             "endpoint_url": os.getenv('AWS_S3_ENDPOINT_URL'),
#             "location":'images',
#             "default_acl": "public-read",
#             "custom_domain": os.getenv('AWS_S3_CUSTOM_DOMAIN'),
#         }
#     },
#     "staticfiles": {
#         "BACKEND": "storages.backends.s3.S3Storage",
#         "OPTIONS": {
#             "access_key": os.getenv('AWS_ACCESS_KEY_ID'),
#             "secret_key": os.getenv('AWS_SECRET_ACCESS_KEY'),
#             "bucket_name": os.getenv('AWS_STORAGE_BUCKET_NAME'),
#             "endpoint_url": os.getenv('AWS_S3_ENDPOINT_URL'),
#             "location":'static',
#             "default_acl": "public-read",
#             "custom_domain": os.getenv('AWS_S3_CUSTOM_DOMAIN'),
#         }
#     },
# }
#okay


STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": os.getenv('AWS_ACCESS_KEY_ID'),
            "secret_key": os.getenv('AWS_SECRET_ACCESS_KEY'),
            "bucket_name": os.getenv('AWS_STORAGE_BUCKET_NAME'),
            "endpoint_url": os.getenv('AWS_S3_ENDPOINT_URL'),
            "location":'images',
            "default_acl": "public-read",
            "custom_domain": os.getenv('AWS_S3_CUSTOM_DOMAIN'),
        }
    },
    # "staticfiles": {
    #     "BACKEND": "storages.backends.s3.S3Storage",
    #     "OPTIONS": {
    #         "access_key": os.getenv('AWS_ACCESS_KEY_ID'),
    #         "secret_key": os.getenv('AWS_SECRET_ACCESS_KEY'),
    #         "bucket_name": os.getenv('AWS_STORAGE_BUCKET_NAME'),
    #         "endpoint_url": os.getenv('AWS_S3_ENDPOINT_URL'),
    #         "location":'static',
    #         "default_acl": "public-read",
    #         "custom_domain": os.getenv('AWS_S3_CUSTOM_DOMAIN'),
    #     }
    # },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Brevo API v3 (direct API calls, no SMTP)
BREVO_API_KEY = os.getenv("SENDINBLUE_API_KEY")
DEFAULT_FROM_EMAIL_ADDRESS = "contact@equitylawandco.com"
DEFAULT_FROM_EMAIL_NAME = "Equity Law & Co."



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
# Media Files Configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CKEditor 5 Configuration
customColorPalette = [
    {
        'color': 'hsl(4, 90%, 58%)',
        'label': 'Red'
    },
    {
        'color': 'hsl(340, 82%, 52%)',
        'label': 'Pink'
    },
    {
        'color': 'hsl(291, 64%, 42%)',
        'label': 'Purple'
    },
    {
        'color': 'hsl(262, 80%, 50%)',
        'label': 'Deep Purple'
    },
    {
        'color': 'hsl(231, 97%, 72%)',
        'label': 'Indigo'
    },
    {
        'color': 'hsl(207, 89%, 56%)',
        'label': 'Blue'
    },
    {
        'color': 'hsl(187, 100%, 42%)',
        'label': 'Cyan'
    },
    {
        'color': 'hsl(174, 100%, 29%)',
        'label': 'Teal'
    },
    {
        'color': 'hsl(122, 39%, 49%)',
        'label': 'Green'
    },
    {
        'color': 'hsl(88, 50%, 53%)',
        'label': 'Light Green'
    },
    {
        'color': 'hsl(66, 100%, 38%)',
        'label': 'Lime'
    },
    {
        'color': 'hsl(60, 100%, 50%)',
        'label': 'Yellow'
    },
    {
        'color': 'hsl(47, 100%, 50%)',
        'label': 'Amber'
    },
    {
        'color': 'hsl(36, 100%, 50%)',
        'label': 'Orange'
    },
    {
        'color': 'hsl(14, 100%, 53%)',
        'label': 'Deep Orange'
    },
    {
        'color': 'hsl(0, 0%, 0%)',
        'label': 'Black'
    },
    {
        'color': 'hsl(0, 0%, 100%)',
        'label': 'White'
    }
]

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'undo', 'redo', '|',
            'formatPainter', '|',
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', 'subscript', 'superscript', '|',
            'removeFormat', '|',
            'fontFamily', 'fontSize', 'fontColor', 'fontBackgroundColor', 'highlight', '|',
            'alignment', 'outdent', 'indent', '|',
            'bulletedList', 'numberedList', 'todoList', '|',
            'link', 'insertImage', 'mediaEmbed', 'insertTable', 'codeBlock', 'blockQuote', 'horizontalLine', '|',
            'sourceEditing', 'showBlocks', 'fullScreen'
        ],
        'heading': {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' },
                { 'model': 'heading4', 'view': 'h4', 'title': 'Heading 4', 'class': 'ck-heading_heading4' },
                { 'model': 'heading5', 'view': 'h5', 'title': 'Heading 5', 'class': 'ck-heading_heading5' },
                { 'model': 'heading6', 'view': 'h6', 'title': 'Heading 6', 'class': 'ck-heading_heading6' },
            ]
        },
        'image': {
            'toolbar': [
                'imageTextAlternative', 'toggleImageCaption', '|',
                'imageStyle:alignLeft', 'imageStyle:alignCenter', 'imageStyle:alignRight', '|',
                'imageStyle:full', 'imageStyle:side', 'linkImage'
            ],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignCenter',
                'alignRight',
            ]
        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells', 'tableProperties', 'tableCellProperties', '|',
                'toggleTableCaption'
            ]
        },
        'list': {
            'properties': {
                'styles': True,
                'startIndex': True,
                'reversed': True,
            }
        },
        'codeBlock': {
            'languages': [
                { 'language': 'python', 'label': 'Python' },
                { 'language': 'javascript', 'label': 'JavaScript' },
                { 'language': 'java', 'label': 'Java' },
                { 'language': 'c', 'label': 'C' },
                { 'language': 'cs', 'label': 'C#' },
                { 'language': 'cpp', 'label': 'C++' },
                { 'language': 'ruby', 'label': 'Ruby' },
                { 'language': 'php', 'label': 'PHP' },
                { 'language': 'typescript', 'label': 'TypeScript' },
                { 'language': 'bash', 'label': 'Bash' },
                { 'language': 'sql', 'label': 'SQL' },
                { 'language': 'html', 'label': 'HTML' },
                { 'language': 'css', 'label': 'CSS' },
                { 'language': 'json', 'label': 'JSON' },
                { 'language': 'xml', 'label': 'XML' },
                { 'language': 'yaml', 'label': 'YAML' },
                { 'language': 'markdown', 'label': 'Markdown' },
                { 'language': 'go', 'label': 'Go' },
                { 'language': 'rust', 'label': 'Rust' },
                { 'language': 'kotlin', 'label': 'Kotlin' },
                { 'language': 'swift', 'label': 'Swift' },
                { 'language': 'r', 'label': 'R' },
                { 'language': 'perl', 'label': 'Perl' },
                { 'language': 'lua', 'label': 'Lua' },
                { 'language': 'vb.net', 'label': 'VB.NET' },
            ]
        },
        'fontFamily': {
            'options': [
                'default',
                'Arial, Helvetica, sans-serif',
                'Courier New, Courier, monospace',
                'Georgia, serif',
                'Lucida Console, Monaco, monospace',
                'Tahoma, Geneva, sans-serif',
                'Times New Roman, Times, serif',
                'Trebuchet MS, sans-serif',
                'Verdana, Geneva, sans-serif',
                'Comic Sans MS, cursive',
                'Palatino Linotype, Book Antiqua, Palatino, serif',
            ],
            'supportAllValues': True
        },
        'fontSize': {
            'options': [
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
                24,
                25,
                26,
                28,
                30,
                32,
                34,
                36,
            ],
            'supportAllValues': True
        },
        'fontColor': {
            'columns': 8,
            'documentColors': 16,
            'colorPicker': True,
        },
        'fontBackgroundColor': {
            'columns': 8,
            'documentColors': 16,
            'colorPicker': True,
        },
        'highlight': {
            'options': [
                {
                    'model': 'yellowMarker',
                    'class': 'marker-yellow',
                    'title': 'Yellow marker',
                    'color': 'var(--ck-highlight_yellow)',
                    'type': 'marker'
                },
                {
                    'model': 'greenMarker',
                    'class': 'marker-green',
                    'title': 'Green marker',
                    'color': 'var(--ck-highlight_green)',
                    'type': 'marker'
                },
                {
                    'model': 'pinkMarker',
                    'class': 'marker-pink',
                    'title': 'Pink marker',
                    'color': 'var(--ck-highlight_pink)',
                    'type': 'marker'
                },
                {
                    'model': 'blueMarker',
                    'class': 'marker-blue',
                    'title': 'Blue marker',
                    'color': 'var(--ck-highlight_blue)',
                    'type': 'marker'
                },
            ]
        },
        'alignment': {
            'options': ['left', 'center', 'right', 'justify']
        },
        'link': {
            'addTargetToExternalLinks': True,
            'defaultProtocol': 'https://',
            'decorators': {
                'openInNewTab': {
                    'mode': 'automatic',
                    'label': 'Open in a new tab',
                    'attributes': {
                        'target': '_blank',
                        'rel': 'noopener noreferrer'
                    }
                },
                'toggleDownloadable': {
                    'mode': 'manual',
                    'label': 'Downloadable',
                    'attributes': {
                        'download': 'download'
                    }
                }
            }
        },
        'mediaEmbed': {
            'previewsInData': True
        },
        'mention': {
            'feeds': [
                {
                    'marker': '@',
                    'feed': [
                        '@Support',
                        '@Legal',
                        '@Marketing',
                        '@Admin',
                    ],
                    'minimumCharacters': 1
                }
            ]
        },
        'placeholder': 'Enter your rich text content here...',
        'htmlSupport': {
            'allow': [
                {
                    'name': 'img',
                    'attributes': {
                        'src': True,
                        'alt': True,
                        'title': True,
                        'width': True,
                        'height': True,
                    }
                },
                {
                    'name': 'iframe',
                    'attributes': {
                        'src': True,
                        'width': True,
                        'height': True,
                        'frameborder': True,
                        'allow': True,
                        'allowfullscreen': True,
                    }
                },
                {
                    'name': 'div',
                    'attributes': {
                        'class': True,
                        'id': True,
                        'style': True,
                    }
                },
                {
                    'name': 'span',
                    'attributes': {
                        'class': True,
                        'id': True,
                        'style': True,
                    }
                },
            ]
        },
        'ckfinder': {
            'uploadUrl': '/ckeditor5/upload/'
        },
        'language': 'en'
    }
}

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': ['rest_framework.filters.SearchFilter', 'rest_framework.filters.OrderingFilter'],
}

# CORS Configuration
# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:3000',
#     'http://127.0.0.1:3000',
#     'http://192.168.1.214:3000',
# ]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "https://niac.pythonanywhere.com",
    "https://niac.org.np",
]


STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'


STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
